[tool.poetry]
name = "type_ml"
version = "0.1.0"
description = "Final ML Project"
authors = ["vladikuss <vreshetoff@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.3.4"
sklearn = "^0.0"
scikit-learn = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
